#!/bin/bash
export TIMEFORMAT="${PGAPPNAME/#pg_regress\//} %6R"

OUTPUT_DIR="${OUTPUT_DIR:-.}"

PROPS_FILE="${OUTPUT_DIR}/properties.txt"
PROPS_CMD=$(cat <<CMD
psql -AXtq -F "\t" -o "${PROPS_FILE}" \
-c "SELECT name, setting FROM pg_settings WHERE source <> 'default'" \
-c "SELECT 'version', version()" -d regression > /dev/null 2>&1
CMD
)

if [ ! -f "${PROPS_FILE}" ]; then
  flock -n "${PROPS_FILE}" -c "${PROPS_CMD}"
fi

{ { time "$@" 1>&3- 2>&4-; } 2>> "${OUTPUT_DIR}/timing.txt"; } 3>&1 4>&2
